Repository Arquisoft/wiq_en3b, pull requests merged in 2024-04, with the labels that each got.

#105 Updated OpenAPI and Added some fixes for error return in QS
  gatewayservice/openapi.yaml
  questionservice/src/controllers/question-controller.ts
  questionservice/src/services/question-generator.ts
  questionservice/test/question-service.test.ts
Labels: enhancement

#110 Join all the frontend
  webapp/package-lock.json
  webapp/package.json
  webapp/public/assets/locales/en/translation.json
  webapp/public/assets/locales/es/translation.json
  webapp/public/assets/locales/fr/translation.json
  webapp/src/App.js
  webapp/src/assets/medal-bronze.svg
  webapp/src/assets/medal-gold.svg
  webapp/src/assets/medal-silver.svg
  webapp/src/assets/moon-solid.svg
  webapp/src/assets/music.mp3
  webapp/src/assets/mute.svg
  webapp/src/assets/sound.svg
  webapp/src/components/Answer/AnswerItem.css
  webapp/src/components/AudioButton/AudioButton.css
  webapp/src/components/AudioButton/AudioButton.js
  webapp/src/components/FinalResult/FinalResult.js
  webapp/src/components/Header/Header.css
  webapp/src/components/Header/Header.js
  webapp/src/components/LanguageSelector/LanguageSelector.css
  webapp/src/components/LanguageSelector/LanguageSelector.js
  webapp/src/components/Nav/Nav.js
  webapp/src/components/Quiz/Question.css
  webapp/src/components/Quiz/Question.js
  webapp/src/components/Quiz/Quiz.js
  webapp/src/components/Slider/ContinuousSlider.js
  webapp/src/index.css
  webapp/src/index.js
  webapp/src/pages/AppLayout.js
  webapp/src/pages/Game/Game.css
  webapp/src/pages/Game/Game.js
  webapp/src/pages/Leaderboard/Leaderboard.js
  webapp/src/pages/Profile/Profile.js
  webapp/src/pages/Settings/Settings.css
  webapp/src/pages/Settings/Settings.js
  webapp/src/utils/formatTime.js
Labels: enhancement

#112 Updating docs
  docs/deploymentGuide.md
  docs/images/03_business_context.png
  docs/images/03_technical_context.png
  docs/plantumls/business-context.wsd
  docs/plantumls/technical-context.wsd
  docs/src/01_introduction_and_goals.adoc
  docs/src/02_architecture_constraints.adoc
  docs/src/03_system_scope_and_context.adoc
  docs/src/04_solution_strategy.adoc
  docs/src/05_building_block_view.adoc
  docs/src/06_runtime_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/08_concepts.adoc
  docs/src/11_technical_risks.adoc
  docs/src/12_glossary.adoc
Labels: documentation

#116 Deployment Prepared
  .github/workflows/build.yml
  .github/workflows/release.yml
  gatewayservice/src/app.ts
  questionservice/Dockerfile
  questionservice/src/services/translation-service.ts
  webapp/Dockerfile
  webapp/src/utils/constants.js
Labels: enhancement

#117 Doc09
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#122 Removed code smells from QuestionService
  questionservice/src/index.ts
  questionservice/src/services/question-generator.ts
  questionservice/src/utils/validations.ts
  questionservice/test/question-generator.test.ts
Labels: bug

#128 Fixed minor code smell in userservice
  users/userservice/src/index.ts
Labels: bug

#158 Move WebApp to port 80
  .env
  .github/workflows/release.yml
  docker-compose.yml
  gatewayservice/Dockerfile
  gatewayservice/src/app.ts
  webapp/Dockerfile
  webapp/e2e/steps/game-page.steps.js
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/profile-page.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/package.json
Labels: enhancement

#161 Fixed translation to french
  questionservice/src/services/translation-service.ts
  questionservice/test/question-generator.test.ts
Labels: bug

#163 Implemented HTTPS in the gateway
  .github/workflows/build.yml
  .github/workflows/release.yml
  gatewayservice/Dockerfile
  gatewayservice/certificate/certificate.crt
  gatewayservice/certificate/certificatekey.key
  gatewayservice/openapi.yaml
  gatewayservice/src/app.ts
  gatewayservice/src/index.ts
  gatewayservice/test/gateway-service.test.ts
  webapp/.env
  webapp/Dockerfile
  webapp/README.md
  webapp/e2e/steps/game-page.steps.js
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/login-form.utils.js
  webapp/e2e/steps/profile-page.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/utils/constants.js
Labels: enhancement

#164 Custom gamemode
  sonar-project.properties
  webapp/e2e/features/start-game.feature
  webapp/e2e/steps/game-page.steps.js
  webapp/src/components/Answer/AnswerItem.js
  webapp/src/components/Answer/AnswerList.js
  webapp/src/components/Button/Button.css
  webapp/src/components/FinalResult/FinalResult.js
  webapp/src/components/GameModes/Classic.js
  webapp/src/components/GameModes/Custom.css
  webapp/src/components/GameModes/Custom.js
  webapp/src/components/Quiz/Question.js
  webapp/src/components/Quiz/Quiz.css
  webapp/src/components/Quiz/Quiz.js
  webapp/src/components/Quiz/Timer.css
  webapp/src/components/Quiz/Timer.js
  webapp/src/components/test/AnswerItem.test.js
  webapp/src/components/test/AnswerList.test.js
  webapp/src/components/test/AudioButton.test.js
  webapp/src/components/test/Classic.test.js
  webapp/src/components/test/Custom.test.js
  webapp/src/components/test/Game.test.js
  webapp/src/components/test/Nav.test.js
  webapp/src/components/test/Question.test.js
  webapp/src/components/test/Settings.test.js
  webapp/src/components/test/index.test.js
  webapp/src/components/test/utils/i18n.test-utils.js
  webapp/src/hooks/useDifficulty.js
  webapp/src/hooks/useGame.js
  webapp/src/hooks/useQuestions.js
  webapp/src/pages/Game/Game.css
  webapp/src/pages/Game/Game.js
  webapp/src/services/apiHistory.js
  webapp/src/services/apiQuestions.js
Labels: enhancement

#159 Change Number Format
  questionservice/src/services/question-generator.ts
  questionservice/src/utils/question-generator-utils.ts
  questionservice/test/question-generator-timeout.test.ts
  questionservice/test/question-generator.test.ts
Labels: enhancement

#160 Limit Question Size
  gatewayservice/openapi.yaml
  questionservice/src/utils/validations.ts
  questionservice/test/question-service.test.ts
  sonar-project.properties
Labels: bug

#166 Public profiles
  webapp/src/App.js
  webapp/src/hooks/useProfile.js
  webapp/src/pages/Leaderboard/Leaderboard.css
  webapp/src/pages/Leaderboard/Leaderboard.js
  webapp/src/pages/Profile/Profile.css
  webapp/src/pages/Profile/Profile.js
Labels: enhancement

#169 HTTPS in the frontend
  .github/workflows/build.yml
  .github/workflows/release.yml
  README.md
  docker-compose.yml
  docs/src/08_concepts.adoc
  gatewayservice/Dockerfile
  gatewayservice/openapi.yaml
  gatewayservice/src/app.ts
  webapp/Dockerfile
  webapp/README.md
  webapp/certificate/certificate.crt
  webapp/certificate/certificatekey.key
  webapp/e2e/steps/game-page.steps.js
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/profile-page.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/loadTests/user-files/simulations/kaw/ChangeLanguageSimulation.java
  webapp/loadTests/user-files/simulations/kaw/GameSimulation.java
  webapp/loadTests/user-files/simulations/kaw/LeaderboardSimulation.java
  webapp/loadTests/user-files/simulations/kaw/LogInSimulation.java
  webapp/loadTests/user-files/simulations/kaw/MusicSimulation.java
  webapp/package.json
Labels: enhancement

#173 Added sortby to /history/leaderboard
  gatewayservice/openapi.yaml
  users/userservice/src/controllers/history-controller.ts
  users/userservice/test/user-service.test.ts
Labels: enhancement

#176 Hardcore mode
  webapp/e2e/steps/game-page.steps.js
  webapp/src/components/Answer/AnswerItem.js
  webapp/src/components/Base.css
  webapp/src/components/FinalResult/FinalResult.js
  webapp/src/components/GameModes/Classic.js
  webapp/src/components/GameModes/Custom.js
  webapp/src/components/GameModes/Hardcore.js
  webapp/src/components/Header/Header.css
  webapp/src/components/Quiz/Question.js
  webapp/src/components/Quiz/Quiz.css
  webapp/src/components/test/AnswerItem.test.js
  webapp/src/components/test/FinalResult.test.js
  webapp/src/components/test/Hardcore.test.js
  webapp/src/components/test/Question.test.js
  webapp/src/components/test/Timer.test.js
  webapp/src/hooks/useGame.js
  webapp/src/hooks/useQuestions.js
  webapp/src/index.css
  webapp/src/pages/Game/Game.css
  webapp/src/pages/Game/Game.js
Labels: enhancement

#182 Added Some Question Templates
  .env
  questionservice/src/models/template-model.ts
  questionservice/src/services/question-generator.ts
  questionservice/test/question-generator.test.ts
  sonar-project.properties
Labels: enhancement

#184 Custom gamemode option to select question types - Fixed tests
  webapp/e2e/steps/login-form.utils.js
  webapp/e2e/steps/profile-page.utils.js
  webapp/e2e/steps/register-form.utils.js
  webapp/public/assets/locales/en/translation.json
  webapp/public/assets/locales/es/translation.json
  webapp/public/assets/locales/fr/translation.json
  webapp/public/assets/locales/uk/translation.json
  webapp/src/components/FinalResult/FinalResult.js
  webapp/src/components/GameModes/Classic.js
  webapp/src/components/GameModes/Custom.js
  webapp/src/components/GameModes/Hardcore.js
  webapp/src/components/QuestionTypeSelector/QuestionTypeSelector.css
  webapp/src/components/QuestionTypeSelector/QuestionTypeSelector.js
  webapp/src/components/Quiz/Question.js
  webapp/src/components/test/AddUser.test.js
  webapp/src/components/test/Classic.test.js
  webapp/src/components/test/Custom.test.js
  webapp/src/components/test/FinalResult.test.js
  webapp/src/components/test/Game.test.js
  webapp/src/components/test/Hardcore.test.js
  webapp/src/components/test/Home.test.js
  webapp/src/components/test/Login.test.js
  webapp/src/components/test/Question.test.js
  webapp/src/components/test/QuestionTypeSelector.test.js
  webapp/src/components/test/Register.test.js
  webapp/src/hooks/useDifficulty.js
  webapp/src/hooks/useGame.js
  webapp/src/hooks/useQuestionTypes.js
  webapp/src/hooks/useQuestions.js
  webapp/src/pages/Game/Game.js
  webapp/src/services/apiQuestions.js
Labels: enhancement

#186 Show more button in leaderboard
  webapp/src/pages/Leaderboard/Leaderboard.css
  webapp/src/pages/Leaderboard/Leaderboard.js
Labels: enhancement

#187 Monitoring on HTTPS!!
  docker-compose.yml
  gatewayservice/monitoring/grafana/provisioning/dashboards/example-service-dashboard.json
  gatewayservice/monitoring/prometheus/prometheus.yml
Labels: bug

#191 Monitoring Dockerfiles
  gatewayservice/monitoring/grafana/Dockerfile
  gatewayservice/monitoring/prometheus/Dockerfile
Labels: bug

#206 Added More Templates
  questionservice/src/models/template-model.ts
  webapp/public/assets/locales/en/translation.json
  webapp/public/assets/locales/es/translation.json
  webapp/public/assets/locales/fr/translation.json
  webapp/public/assets/locales/uk/translation.json
Labels: enhancement

#208 Modified grafana to use https
  .github/workflows/release.yml
  docker-compose.yml
  gatewayservice/monitoring/grafana/grafana.ini
Labels: enhancement

#218 Error with entitites fixed and minor improvements to templates
  questionservice/src/models/template-model.ts
  questionservice/src/services/question-generator.ts
Labels: enhancement
