Repository Arquisoft/wiq_en3b, pull requests merged in 2024-03, with the labels that each got.

#48 Question Service
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/src/controllers/question-controller.ts
  questionservice/src/models/question-model.ts
  questionservice/src/services/question-generator.ts
Labels: enhancement

#50 Reviewed Part4 of Documentation
  docs/src/04_solution_strategy.adoc
Labels: documentation

#35 Doc12
  docs/src/12_glossary.adoc
Labels: documentation

#57 Part 11 of Documentation
  docs/src/11_technical_risks.adoc
Labels: documentation

#56 Doc08
  docs/src/08_concepts.adoc
Labels: documentation

#78 Questionservice Tests and Refactoring
  .github/workflows/build.yml
  questionservice/jest.config.js
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/src/controllers/question-controller.ts
  questionservice/src/routes/question-routes.ts
  questionservice/src/services/question-generator.ts
  questionservice/src/utils/validations.ts
  questionservice/test/question-generator.test.ts
  questionservice/test/question-service.test.ts
Labels: enhancement

#84 Small changes to sonar-project.properties
  sonar-project.properties
Labels: enhancement

#83 Added OpenAPI specification
  gatewayservice/openapi.yaml
  gatewayservice/package-lock.json
  gatewayservice/package.json
  gatewayservice/src/app.ts
Labels: enhancement

#87 Handling internal server errors
  users/authservice/src/controllers/auth-controller.ts
  users/userservice/src/controllers/history-controller.ts
  users/userservice/src/controllers/user-controller.ts
Labels: bug

#91 Added Internal Server Errors documentation
  gatewayservice/openapi.yaml
Labels: enhancement

#90 Small changes to jest configuration
  gatewayservice/jest.config.js
  questionservice/jest.config.js
  sonar-project.properties
  users/authservice/jest.config.js
  users/userservice/jest.config.js
  users/utils/jest.config.js
  users/utils/tsconfig.json
Labels: bug

#95 Image Questions
  questionservice/src/models/question-model.ts
  questionservice/src/services/question-generator.ts
  questionservice/test/question-generator.test.ts
Labels: enhancement

#97 Added tests for internal server errors
  users/authservice/test/auth-service.test.ts
  users/userservice/test/user-service.test.ts
  users/utils/package-lock.json
  users/utils/test/users-utils.test.ts
Labels: enhancement

#98 Some changes to improve quality
  gatewayservice/src/app.ts
  gatewayservice/test/gateway-service.test.ts
  questionservice/src/app.ts
  sonar-project.properties
  users/authservice/src/app.ts
  users/userservice/src/app.ts
Labels: enhancement

#96 Timeout and Number of questions retrieval
  questionservice/jest.config.js
  questionservice/src/services/question-generator.ts
  questionservice/src/utils/question-generator-utils.ts
  questionservice/test/question-generator-timeout.test.ts
  questionservice/test/question-generator.test.ts
  questionservice/test/question-service.test.ts
Labels: bug, enhancement

#102 Profile endpoints
  gatewayservice/src/controllers/user-controller.ts
  gatewayservice/src/routes/user-routes.ts
  gatewayservice/test/gateway-service.test.ts
  users/authservice/package-lock.json
  users/userservice/package-lock.json
  users/userservice/package.json
  users/userservice/src/controllers/user-controller.ts
  users/userservice/src/middlewares/protect-middleware.ts
  users/userservice/src/routes/user-routes.ts
  users/userservice/src/types.d.ts
  users/userservice/src/utils/profile-body-validation.ts
  users/userservice/test/user-service.test.ts
  users/utils/package.json
  users/utils/src/models.ts
Labels: enhancement
